apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: comp-test
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: MY_FAKE_ENV_VAR
          value: "100"
        image: quay.io/abarbaro-org/spi-demos-olfp-tenant/rsenvapp/comp-test@sha256:8415beb7972976c6b3d9dbd7aae2e8724fbf7ca219e672c66c916cf262427bad
        name: my-java-quarkus
        resources: {}
status: {}
